const mydate= new Date()
console.log(mydate.toDateString())
console.log(mydate.toISOString())
console.log(mydate.toJSON())
console.log(mydate.toLocaleString())
console.log(mydate.toString())
let mynewdate= new Date(2024,1,18)
console.log(mynewdate.toDateString())
console.log(Math.floor(Date.now()/1000))
console.log(mydate.toLocaleDateString('default',{weekday:"long"}))